services:
  web:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

